FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install streamlit & plotly khusus untuk dashboard
RUN pip install --no-cache-dir streamlit plotly

COPY . .

EXPOSE 8501

# Jalankan streamlit
ENTRYPOINT ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
