version: '3.8'

services:
  # 1. Core Engine Bot
  sigcrypt-engine:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sigcrypt_engine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    network_mode: "host"

  # 2. Dashboard Microservice
  sigcrypt-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: sigcrypt_dashboard
    restart: unless-stopped
    volumes:
      - ./data:/app/data # BAGI FOLDER YANG SAMA DENGAN ENGINE
    network_mode: "host"
    environment:
      - MODE=1 # Dashboard tidak butuh mode, tapi wajib punya env dasar
